-- Run this in your Supabase SQL Editor

create table messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null
);

-- Optional: Enable Row Level Security (RLS) if you want to restrict access
alter table messages enable row level security;

-- Allow anyone to insert (since it's a public contact form)
create policy "Enable insert for everyone" on messages for insert with check (true);

-- Only allow you (authenticated users or specific roles) to select/view
-- For simplicity in a portfolio, you might just use the dashboard to view data.
